### ISSUE TITLE
Error shows up when user is not an affiliate

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/affiliatewp-show-affiliate-coupons#11]
When you are not an affiliate, I am shown an error. The function get_coupons() looks for the affiliate_id of the current logged user, but it returns NULL if the current user is not an affiliate.

Ticket: https://secure.helpscout.net/conversation/460648130/69730/.

**Comment by michaelbeil** [comment]
https://secure.helpscout.net/conversation/463385956/69969/?folderId=634609

**Comment by amdrew** [comment]
@michaelbeil Can you list your steps to replicate?

**Comment by michaelbeil** [comment]
Create a new user who is not an affiliate.

Log in with that user account.

An error should appear in the error log.

**Comment by amdrew** [comment]
Replicated the error while viewing the site as a logged out user.

@michaelbeil I'm not seeing the error when I create a new user account (not an affiliate) and log in. Can you show me a quick video of the error appearing after logging in?

**Comment by michaelbeil** [comment]
Well, that is odd. I cannot replicate this as a logged user.

**Comment by amdrew** [comment]
How strange! Ok, going to push a release out soon.

**Comment by michaelbeil** [comment]
I think we can close this out.
