### ISSUE TITLE
MemberPress: Express coupon types as percentage/flat vs percent/dollars

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/affiliatewp-show-affiliate-coupons#24]
As reported by a customer, (https://secure.helpscout.net/conversation/1010196236/137345?folderId=1170842), we're outputting what are effectively the raw coupon types as stored by MemberPress after the amounts. The issue is that the raw types are "dollar" and "percent" and if the customer is not using USD, for instance, as their currency, you can see the problem with that.

![Customer example](https://p199.p4.n0.cdn.getcloudapp.com/items/xQu0KLvL/mp_coupons.png?v=bb910387cb485b43993ef621ba94129c)

In order to not get down a rabbit hole of trying to determine the MemberPress currency, I think we should go with reverting to our tried and tested vernacular of flat/percentage vs the raw values of dollar/percent

**Comment by DrewAPicture** [comment]
PR: #25 

@gspice If you could please have the customer test the PR as a patched version, it would be appreciated. The PR introduces two translatable strings, 'flat' to replace 'dollar', and 'percentage' to replace 'percent'. I saw the customer is running Loco Translate, so they could use that to translate them directly.

**Comment by michaelbeil** [comment]
The PR changes the strings:
![Screen Capture on 2019-11-29 at 23-43-47](https://user-images.githubusercontent.com/4752949/69892121-790d5280-1302-11ea-911a-f02719841499.gif)

I used Loco Translate to change the string from flat to **€**: 
![Screen Capture on 2019-11-30 at 00-01-33](https://user-images.githubusercontent.com/4752949/69892374-18334980-1305-11ea-9579-736cd81b50a8.gif)

**Comment by michaelbeil** [comment]
@gspice sent the new version to the customer and they replied:
>Yes that worked perfectly.
>Thank you!

**Comment by DrewAPicture** [comment]
Merged #25.
