### ISSUE TITLE
Add Support for MemberPress

### ISSUE THREAD

**Issue by nikolov-tmw** [AffiliateWP/affiliatewp-show-affiliate-coupons#4]
We're using MemberPress to manage memberships and subscriptions and we want to use affiliate coupons as a way to promote the platform. I've got AffiliateWP all set-up and I also installed this plugin in order to display the available coupons in the Affiliate's dashboard and I saw that it's not working.
Looking into the code I found out that this integration is not currently supported.

I tweaked the code a bit and it seems to be working properly now. I'll be submitting a PR soon - feel free to include it in the plugin :smile:

**Comment by ramiabraham** [comment]
Hey @nikolov-tmw ,

Thank you for adding this! This does show the coupon info in the AffiliateWP affiliate area.

----

A minor issue:

- Despite the notice _"You cannot create coupons until you have added at least 1 Membership."_ shown in MemberPress when creating a coupon and no Memberships exist, `draft` coupons are still shown when queried.

    When this occurs, the result in the AffiliateWP affiliate area is a string that may confuse customers settings things up (or their affiliates):

![dashboard](http://i.imgur.com/uMwNsxw.png "affwp AA appearance, after MP addition of coupon when no MP memberships exist")

To replicate, freshly install MemberPress `1.2.8b23`

I recommend specifying the `post_status` of the coupon to resolve this.

**Comment by ramiabraham** [comment]
@nikolov-tmw I went ahead and added that check (was a pretty small adjustment). We'll get this into the next release. Thanks!

**Comment by nikolov-tmw** [comment]
I didn't think about that edge case. Thank you for fixing that! Don't mean to be pushy, but do you have an idea when you'll be releasing the next version? I need to know whether to patch this up for now(we're pushing AffiliateWP into production in our app on Monday).

In any case thank you for the quick response and merge - highly appreciated :+1:

**Comment by ramiabraham** [comment]
At this time we don't have a date, but we'll update this thread once it goes out.

**Comment by nikolov-tmw** [comment]
@ramiabraham actually since we're using Composer, I'll just lock the dependency to the latest commit on master until the next version is released :smiley:
