### ISSUE TITLE
Show coupon tab before the log out tab

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/affiliatewp-show-affiliate-coupons#6]
![screen shot 2016-11-01 at 20 19 23](https://cloud.githubusercontent.com/assets/4752949/19903898/a3597d50-a070-11e6-816c-4b98c6dec700.png)

**Comment by sumobi** [comment]
https://github.com/AffiliateWP/AffiliateWP/issues/1778

**Comment by michaelbeil** [comment]
Closing since AffiliateWP/AffiliateWP#1778 is merged into core.
