### ISSUE TITLE
Add responsive styling for table

### ISSUE THREAD

**Issue by gspice** [AffiliateWP/affiliatewp-show-affiliate-coupons#9]
Add new styling for responsive coupon table as completed for the affiliate area: 
https://github.com/AffiliateWP/AffiliateWP/issues/2349

**Comment by amdrew** [comment]
Done!

<img width="315" alt="screenshot 2017-11-01 16 02 00" src="https://user-images.githubusercontent.com/52581/32259407-41cbd78e-bf25-11e7-8963-2b33bb899f59.png">
